// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmzlH9UhJr7tzLrq5YwQD1SZ97Ge3DHrI',
    appId: '1:388036390067:android:b44d69ac879d42093294c6',
    messagingSenderId: '388036390067',
    projectId: 'stocodi-app-360ec',
    databaseURL: 'https://stocodi-app-360ec-default-rtdb.firebaseio.com',
    storageBucket: 'stocodi-app-360ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSsCKixj9ulC1aoe6r5l5tahfY0wiR7WA',
    appId: '1:388036390067:ios:509bfd6d00fa352d3294c6',
    messagingSenderId: '388036390067',
    projectId: 'stocodi-app-360ec',
    databaseURL: 'https://stocodi-app-360ec-default-rtdb.firebaseio.com',
    storageBucket: 'stocodi-app-360ec.appspot.com',
    iosBundleId: 'com.example.stocodiApp',
  );
}
